apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: transaction-fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: transaction-producer:1.0
        imagePullPolicy: IfNotPresent
